### ISSUE TITLE
Redundancy of ANT_HOME and ANT_DIR

### ISSUE THREAD

**Issue by Remigius2011** [dennisg/heroku-buildpack-ant#2]
There are two almost identical definitions:

in bin/common:

ANT_HOME=.buildpack/apache-ant-$ANT_VER

in bin/compile:

VENDORING_DIR="$BUILD_DIR/.buildpack"
ANT_DIR="$VENDORING_DIR/apache-ant-$ANT_VER"

As the prefix $BUILD_DIR/ is only set in compile, this may be error
prone. Is ANT_HOME used at all? (It might be used in build scripts for some purposes, though).

**Comment by dennisg** [comment]
hi Remigius,
i've created a develop branch that works for me. can you have a look at it? 

there were actually reasons for the multiple definitions, since at the different stages of getting the slug up and running, the actual location of the data changes.

cheers, dennis

**Comment by Remigius2011** [comment]
Hi Dennis,

I'm currently ill but will look at it after returning to the office.

Cheers, Remigius.
Am 02.02.2014 12:41 schrieb "Dennis Geurts" notifications@github.com:

**Comment by Remigius2011** [comment]
Hi Dennis,

I have just reviewed your changes and imho they look sound. I saw you got
completely rid of ANT_DIR, which is good.

Cheers, R.

**Comment by dennisg** [comment]
Thanks for the review! I'll pull this branch to master

**Comment by dennisg** [comment]
merged

**Comment by Remigius2011** [comment]
Hi Dennis,

I've just deployed a new version into the test environment and the new
version of the build pack worked just fine.

Best regards and thanks for the good work,

Remigius.

**Comment by dennisg** [comment]
great! thanks for using the buildpack and your valued input.

cheers, dennid
